### ISSUE TITLE
node_modules shouldn't be commited to source control

### ISSUE THREAD

**Issue by soryy708** [pvorb/node-sha1#11]
[https://github.com/pvorb/node-sha1/tree/master/node_modules](node_modules) is in source control right now. Add all of it to [`.gitignore`](https://github.com/pvorb/node-sha1/blob/master/.gitignore).

**Comment by pvorb** [comment]
No. It worked fine with `node_modules` under source control all those years, so I'll leave it this way.

**Comment by soryy708** [comment]
https://www.quora.com/Should-I-put-node_modules-in-gitignore

**Comment by soryy708** [comment]
https://pragprog.com/the-pragmatic-programmer/extracts/coincidence

**Comment by pvorb** [comment]
Where is the downside of having the node_modules in Git?

**Comment by soryy708** [comment]
Here: https://www.quora.com/Should-I-put-node_modules-in-gitignore
