### ISSUE TITLE
Document magic numbers

### ISSUE THREAD

**Issue by soryy708** [pvorb/node-sha1#12]
[`H0`, `H1`, `H2`, `H3`, and `H4`](https://github.com/pvorb/node-sha1/blob/master/sha1.js#L21) are non-trivial magic numbers. Add documentation.

Are these [nothing-up-my-sleeve numbers](https://en.wikipedia.org/wiki/Nothing-up-my-sleeve_number)?

**Comment by pvorb** [comment]
See https://crypto.stackexchange.com/q/10829 if you are interested.
