### ISSUE TITLE
Base64 functionality

### ISSUE THREAD

**Issue by patroldo** [pvorb/node-sha1#9]
Hi
Actually it's not an issue, it's more like demande to add base64 output flag.  Below provide code to do so. Please, add it into your repository :)

        options && options.asBase64 ? crypt.bytesToBase64(digestbytes) :

Finally it should look like follow:
```
// Public API
  api = function (message, options) {
    var hash = sha1(message);
    var digestbytes = crypt.wordsToBytes(hash);//asBase64
    return options && options.asBytes ? digestbytes :
        options && options.asString ? bin.bytesToString(digestbytes) :
        options && options.asBase64 ? crypt.bytesToBase64(digestbytes) :
        crypt.bytesToHex(digestbytes);
  };
```
If you do so, i'll be so pleasured :))

**Comment by pvorb** [comment]
Sorry, but if you really need this feature, you can get it by sticking together something that parses hex and that can output base64.
